"use client";

import * as LucideIcons from "lucide-react";
import type { LucideProps } from "lucide-react";
import type { ForwardRefExoticComponent, RefAttributes } from "react";

// Define the type for a valid Lucide icon component
type LucideIconType = ForwardRefExoticComponent<Omit<LucideProps, 'ref'> & RefAttributes<SVGSVGElement>>;
type IconName = keyof typeof LucideIcons;

// Create a type guard to check if the accessed property is a valid icon component
const isValidLucideIcon = (icon: any): icon is LucideIconType => {
  // More permissive check - just ensure it's a function that can be used as a component
  return typeof icon === "function" && icon !== LucideIcons.createLucideIcon;
};

// Common icon name mappings to handle variations
const ICON_NAME_MAPPINGS: Record<string, string> = {
  // Direct mappings for common variations
  'LayoutDashboard': 'LayoutDashboard',
  'FileText': 'FileText',
  'Home': 'Home',
  'Newspaper': 'Newspaper',
  'ShoppingCart': 'ShoppingCart',
  'Package': 'Package',
  'ShoppingBag': 'ShoppingBag',
  'Percent': 'Percent',
  'GalleryHorizontal': 'GalleryHorizontal',
  'File': 'File',
  'Youtube': 'Youtube',
  'Users': 'Users',
  'Mail': 'Mail',
  'Mailbox': 'Mailbox',
  'Settings': 'Settings',
  'Menu': 'Menu',
  'ToyBrick': 'ToyBrick',
  'ArrowRightLeft': 'ArrowRightLeft',
  'Globe': 'Globe',
  'Blocks': 'Blocks',
  'Mails': 'Mails',
  'Shield': 'Shield',
  // Additional common variations
  'layout-dashboard': 'LayoutDashboard',
  'file-text': 'FileText',
  'shopping-cart': 'ShoppingCart',
  'shopping-bag': 'ShoppingBag',
  'arrow-right-left': 'ArrowRightLeft',
  'gallery-horizontal': 'GalleryHorizontal',
  'toy-brick': 'ToyBrick',
  'mail-box': 'Mailbox',
  'global': 'Globe',
  'block': 'Blocks',
  'email': 'Mails',
  'admin': 'Shield',
  // Fallbacks for common naming patterns
  'dashboard': 'LayoutDashboard',
  'content': 'FileText',
  'blog': 'Newspaper',
  'ecommerce': 'ShoppingCart',
  'products': 'Package',
  'orders': 'ShoppingBag',
  'coupons': 'Percent',
  'galleries': 'GalleryHorizontal',
  'pdf': 'File',
  'youtube': 'Youtube',
  'engagement': 'Users',
  'contacts': 'Mail',
  'subscribers': 'Mailbox',
  'configuration': 'Settings',
  'widgets': 'ToyBrick',
  'redirects': 'ArrowRightLeft',
  'menus': 'Menu',
  'user': 'Users',
  'files': 'File',
  'videos': 'Youtube',
  // Additional mappings for better coverage
  'user-group': 'Users',
  'user-plus': 'UserPlus',
  'user-minus': 'UserMinus',
  'user-check': 'UserCheck',
  'user-x': 'UserX',
  'lock': 'Lock',
  'unlock': 'Unlock',
  'key': 'Key',
  'calendar': 'Calendar',
  'clock': 'Clock',
  'bell': 'Bell',
  'heart': 'Heart',
  'star': 'Star',
  'bookmark': 'Bookmark',
  'tag': 'Tag',
  'image': 'Image',
  'video': 'Video',
  'music': 'Music',
  'map': 'Map',
  'location': 'MapPin',
  'phone': 'Phone',
  'send': 'Send',
  'link': 'Link',
  'unlink': 'Unlink',
  'copy': 'Copy',
  'clipboard': 'Clipboard',
  'download': 'Download',
  'upload': 'Upload',
  'trash': 'Trash',
  'edit': 'Edit',
  'save': 'Save',
  'search': 'Search',
  'filter': 'Filter',
  'sort': 'SortAsc',
  'eye': 'Eye',
  'eye-off': 'EyeOff',
  'plus': 'Plus',
  'minus': 'Minus',
  'check': 'Check',
  'x': 'X',
  'alert': 'AlertTriangle',
  'info': 'Info',
  'help': 'HelpCircle',
  'warning': 'AlertTriangle',
  'error': 'AlertCircle',
  'success': 'CheckCircle',
  'cancel': 'XCircle',
  'refresh': 'RefreshCw',
  'rotate': 'RotateCw',
  'undo': 'Undo',
  'redo': 'Redo',
  'zoom-in': 'ZoomIn',
  'zoom-out': 'ZoomOut',
  'maximize': 'Maximize',
  'minimize': 'Minimize',
  'expand': 'Expand',
  'collapse': 'Collapse',
  'more': 'MoreHorizontal',
  'dots': 'MoreHorizontal',
  'options': 'Settings',
  'tools': 'Wrench',
  'wrench': 'Wrench',
  'hammer': 'Hammer',
  'code': 'Code',
  'terminal': 'Terminal',
  'command': 'Terminal',
  'database': 'Database',
  'server': 'Server',
  'cloud': 'Cloud',
  'cloud-upload': 'CloudUpload',
  'cloud-download': 'CloudDownload',
  'wifi': 'Wifi',
  'bluetooth': 'Bluetooth',
  'printer': 'Printer',
  'camera': 'Camera',
  'mic': 'Mic',
  'volume': 'Volume2',
  'mute': 'VolumeX',
  'play': 'Play',
  'pause': 'Pause',
  'stop': 'Square',
  'skip-forward': 'SkipForward',
  'skip-back': 'SkipBack',
  'rewind': 'Rewind',
  'fast-forward': 'FastForward',
  'repeat': 'Repeat',
  'shuffle': 'Shuffle',
  'list': 'List',
  'grid': 'Grid',
  'table': 'Table',
  'chart': 'BarChart',
  'pie-chart': 'PieChart',
  'bar-chart': 'BarChart',
  'line-chart': 'TrendingUp',
  'trending-up': 'TrendingUp',
  'trending-down': 'TrendingDown',
  'activity': 'Activity',
  'pulse': 'Activity',
  'heart-pulse': 'HeartPulse',
  'cpu': 'Cpu',
  'memory': 'Memory',
  'hard-drive': 'HardDrive',
  'usb': 'Usb',
  'battery': 'Battery',
  'battery-charging': 'BatteryCharging',
  'power': 'Power',
  'zap': 'Zap',
  'lightning': 'Zap',
  'sun': 'Sun',
  'moon': 'Moon',
  'cloud-sun': 'CloudSun',
  'cloud-moon': 'CloudMoon',
  'cloud-rain': 'CloudRain',
  'cloud-snow': 'CloudSnow',
  'cloud-lightning': 'CloudLightning',
  'wind': 'Wind',
  'droplet': 'Droplet',
  'umbrella': 'Umbrella',
  'flag': 'Flag',
  'bookmark-check': 'BookmarkCheck',
  'bookmark-x': 'BookmarkX',
  'bookmark-plus': 'BookmarkPlus',
  'bookmark-minus': 'BookmarkMinus',
  'folder': 'Folder',
  'folder-open': 'FolderOpen',
  'folder-plus': 'FolderPlus',
  'folder-minus': 'FolderMinus',
  'file-image': 'FileImage',
  'file-video': 'FileVideo',
  'file-audio': 'FileAudio',
  'file-code': 'FileCode',
  'file-archive': 'FileArchive',
  'file-pdf': 'FileText',
  'file-word': 'FileText',
  'file-excel': 'FileText',
  'file-powerpoint': 'FileText',
  'file-plus': 'FilePlus',
  'file-minus': 'FileMinus',
  'file-check': 'FileCheck',
  'file-x': 'FileX',
  'archive': 'Archive',
  'box': 'Box',
  'gift': 'Gift',
  'award': 'Award',
  'trophy': 'Trophy',
  'medal': 'Medal',
  'shield-check': 'ShieldCheck',
  'shield-x': 'ShieldX',
  'lock-open': 'Unlock',
  'log-in': 'LogIn',
  'log-out': 'LogOut',
  'sign-in': 'LogIn',
  'sign-out': 'LogOut',
  'user-circle': 'User',
  'user-square': 'User',
  'group': 'Users',
  'team': 'Users',
  'organization': 'Building',
  'building': 'Building',
  'house': 'Home',
  'apartment': 'Home',
  'store': 'Store',
  'shop': 'ShoppingCart',
  'cart': 'ShoppingCart',
  'basket': 'ShoppingCart',
  'bag': 'ShoppingBag',
  'credit-card': 'CreditCard',
  'wallet': 'Wallet',
  'dollar-sign': 'DollarSign',
  'euro': 'Euro',
  'pound': 'PoundSterling',
  'rupee': 'IndianRupee',
  'yen': 'Yen',
  'bitcoin': 'Bitcoin',
  'ethereum': 'Ethereum',
  'bar-chart-2': 'BarChart2',
  'thermometer': 'Thermometer',
  'airplay': 'Airplay',
  'cast': 'Cast',
  'tv': 'Tv',
  'radio': 'Radio',
  'speaker': 'Speaker',
  'headphones': 'Headphones',
  'mic-off': 'MicOff',
  'volume-1': 'Volume1',
  'volume-2': 'Volume2',
  'volume-x': 'VolumeX',
  'film': 'Film',
  'video-off': 'VideoOff',
  'sliders': 'Sliders',
  'tool': 'Wrench',
  'book': 'Book',
  'book-open': 'BookOpen',
  'alarm': 'AlarmClock',
  'timer': 'Timer',
  'watch': 'Watch',
  'time': 'Clock',
  'hourglass': 'Hourglass',
  'loader': 'Loader',
  'loader-2': 'Loader2',
  'refresh-ccw': 'RefreshCcw',
  'sync': 'RefreshCw',
  'download-cloud': 'CloudDownload',
  'upload-cloud': 'CloudUpload',
  'cloud-off': 'CloudOff',
  'bug': 'Bug',
  'rss': 'Rss',
  'wifi-off': 'WifiOff',
  'bluetooth-off': 'BluetoothOff',
  'scanner': 'Printer',
  'fax': 'Printer',
  'clipboard-check': 'ClipboardCheck',
  'clipboard-x': 'ClipboardX',
  'clipboard-list': 'ClipboardList',
  'clipboard-signature': 'ClipboardSignature',
  'edit-2': 'Edit',
  'edit-3': 'Edit3',
  'pen-tool': 'PenTool',
  'scissors': 'Scissors',
  'trash-2': 'Trash2',
  'share': 'Share',
  'share-2': 'Share2',
  'external-link': 'ExternalLink',
  'at-sign': 'AtSign',
  'mail-open': 'MailOpen',
  'message-circle': 'MessageCircle',
  'message-square': 'MessageSquare',
  'chat': 'MessageCircle',
  'comment': 'MessageCircle',
  'phone-call': 'PhoneCall',
  'phone-incoming': 'PhoneIncoming',
  'phone-outgoing': 'PhoneOutgoing',
  'phone-missed': 'PhoneMissed',
  'phone-off': 'PhoneOff',
  'voicemail': 'Voicemail',
  'smartphone': 'Smartphone',
  'tablet': 'Tablet',
  'laptop': 'Laptop',
  'computer': 'Monitor',
  'monitor': 'Monitor',
  'camera-off': 'CameraOff',
  'image-off': 'ImageOff',
  'move': 'Move',
  'cursor': 'Move',
  'maximize-2': 'Maximize2',
  'minimize-2': 'Minimize2',
  'chevron-up': 'ChevronUp',
  'chevron-down': 'ChevronDown',
  'chevron-left': 'ChevronLeft',
  'chevron-right': 'ChevronRight',
  'arrow-up': 'ArrowUp',
  'arrow-down': 'ArrowDown',
  'arrow-left': 'ArrowLeft',
  'arrow-right': 'ArrowRight',
  'arrow-up-circle': 'ArrowUpCircle',
  'arrow-down-circle': 'ArrowDownCircle',
  'arrow-left-circle': 'ArrowLeftCircle',
  'arrow-right-circle': 'ArrowRightCircle',
  'corner-up-left': 'CornerUpLeft',
  'corner-up-right': 'CornerUpRight',
  'corner-down-left': 'CornerDownLeft',
  'corner-down-right': 'CornerDownRight',
  'swap': 'Swap',
  'swap-horizontal': 'SwapHorizontal',
  'swap-vertical': 'SwapVertical',
  'corner-left-up': 'CornerLeftUp',
  'corner-right-up': 'CornerRightUp',
  'corner-left-down': 'CornerLeftDown',
  'corner-right-down': 'CornerRightDown',
  'align-left': 'AlignLeft',
  'align-center': 'AlignCenter',
  'align-right': 'AlignRight',
  'align-justify': 'AlignJustify',
  'list-ordered': 'ListOrdered',
  'list-unordered': 'List',
  'unordered-list': 'List',
  'ordered-list': 'ListOrdered',
  'list-check': 'ListChecks',
  'check-list': 'ListChecks',
  'list-checks': 'ListChecks',
  'check-square': 'CheckSquare',
  'square': 'Square',
  'plus-square': 'PlusSquare',
  'minus-square': 'MinusSquare',
  'x-square': 'XSquare',
  'check-circle': 'CheckCircle',
  'circle': 'Circle',
  'plus-circle': 'PlusCircle',
  'minus-circle': 'MinusCircle',
  'x-circle': 'XCircle',
  'help-circle': 'HelpCircle',
  'alert-circle': 'AlertCircle',
  'alert-triangle': 'AlertTriangle',
  'stop-circle': 'StopCircle',
  'x-octagon': 'XOctagon',
  'alert-octagon': 'AlertOctagon',
  'shield-alert': 'ShieldAlert',
  'shield-off': 'ShieldOff',
  'zap-off': 'ZapOff',
  'battery-full': 'BatteryFull',
  'battery-medium': 'BatteryMedium',
  'battery-low': 'BatteryLow',
  'battery-empty': 'BatteryEmpty',
  'battery-warning': 'BatteryWarning',
  'monitor-speaker': 'MonitorSpeaker',
  'sunrise': 'Sunrise',
  'sunset': 'Sunset',
  'cloud-drizzle': 'CloudDrizzle',
  'map-pin': 'MapPin',
  'map-marker': 'MapPin',
  'navigation': 'Navigation',
  'navigation-2': 'Navigation2',
  'compass': 'Compass',
  'earth': 'Globe',
  'flag-off': 'FlagOff',
  'star-off': 'StarOff',
  'heart-off': 'HeartOff',
  'bookmark-off': 'BookmarkOff',
  'tags': 'Tags'
};

const Icon = ({ name, className }: { name: string; className?: string }) => {
  // Handle empty or undefined names
  if (!name) {
    return <LucideIcons.HelpCircle className={className} />;
  }
  
  // First try direct mapping
  let iconName = name;
  
  // Check if we have a direct mapping
  if (ICON_NAME_MAPPINGS[name]) {
    iconName = ICON_NAME_MAPPINGS[name];
  }
  
  // Try to get the icon from LucideIcons
  let LucideIcon = LucideIcons[iconName as IconName];
  
  // If not found, try with capitalized first letter
  if (!LucideIcon) {
    const capitalizedName = iconName.charAt(0).toUpperCase() + iconName.slice(1);
    LucideIcon = LucideIcons[capitalizedName as IconName];
  }
  
  // If still not found, try direct access with the original name
  if (!LucideIcon && name in LucideIcons) {
    LucideIcon = LucideIcons[name as IconName];
  }
  
  // Validate the icon - check if it's a valid React component
  if (!LucideIcon || 
      (typeof LucideIcon !== 'function' && 
       !(typeof LucideIcon === 'object' && LucideIcon !== null && '$$typeof' in LucideIcon)) || 
      LucideIcon === LucideIcons.createLucideIcon) {
    // Only show warning in development mode
    if (process.env.NODE_ENV === 'development') {
      console.warn(`Icon "${name}" not found or invalid, using HelpCircle as fallback`);
    }
    return <LucideIcons.HelpCircle className={className} />;
  }
  
  // Cast to the proper type
  const IconComponent = LucideIcon as LucideIconType;
  
  // Try to render the icon and catch any errors
  try {
    return <IconComponent className={className} />;
  } catch (error) {
    // Only show warning in development mode
    if (process.env.NODE_ENV === 'development') {
      console.warn(`Error rendering icon "${name}", using HelpCircle as fallback:`, error);
    }
    return <LucideIcons.HelpCircle className={className} />;
  }
};

export default Icon;